server:
  port: 8099
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: book2
          uri: http://localhost:8090
          predicates:
            - Path=/book/**
        - id: book2
          uri: http://localhost:8090
          predicates:
            - Path=/borrow/**
        - id: book2
          uri: http://localhost:8090
          predicates:
            - Path=/books
        - id: review
          uri: http://localhost:8092
          predicates:
            - Path=/review/**
        - id: login
          uri: http://localhost:8093
          predicates:
            - Path=/login
